# Generated by Django 4.2.2 on 2023-07-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raca', models.CharField(max_length=50)),
                ('data_criacao', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producao.criacao')),
            ],
        ),
    ]
