# Generated by Django 4.2.2 on 2023-07-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='criacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producao.criacao', verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='criacao',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='criacao',
            name='raca',
            field=models.CharField(max_length=50, verbose_name='Raça'),
        ),
    ]
